# Generated by Django 5.1.3 on 2024-12-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoriya ismini kiriting')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Nashir sanasi')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='Kitobning ISBN raqami')),
                ('genre', models.CharField(max_length=100, verbose_name='Kitob janri')),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.category', verbose_name='categoriya')),
            ],
        ),
    ]
