# Generated by Django 5.1.3 on 2024-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/', verbose_name='kitob rasmi'),
            preserve_default=False,
        ),
    ]
